apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::697208108185:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18A11TCZQY9IP
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::697208108185:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-15T11:33:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-15T11:33:50Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-02-15T12:00:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5846"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dc88770d-79c5-42d3-9f1e-91f78e51fb33
